stages:
    - build
    - deploy

services:
  - docker:dind

# ###Build

build_image:
  stage: build
  image: docker
  variables:
    DOCKER_HOST: tcp://localhost:2375/
    DOCKER_DRIVER: overlay2
  script:
    - |
      date
      whoami
      echo "$CI_REGISTRY_PASSWORD" |  docker login -u "$CI_REGISTRY_USER" $CI_REGISTRY --password-stdin
      echo "===>>> Build image <<<==="
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
  only:
    - master

###DEPLOY

deploy_image:
  stage: deploy
  script:
    - |
      date
      whoami
      echo "$CI_REGISTRY_PASSWORD" | sudo docker login -u "$CI_REGISTRY_USER" $CI_REGISTRY --password-stdin
      echo "===>>> Deploy to production server <<<==="
      sudo docker stop vintauge || true
      sudo docker rm -f vintauge || true
      sudo docker run --network="host" --name=vintauge --restart=always -d -p 3000:3000 $CI_REGISTRY_IMAGE


  only:
    - master
  tags:
    - web-servers
